export const footer = {
    "de": [
        "Sprachauswahl",
        "Informationen",
        "Impressum",
        "Datenschutz",
        "Kontakt",
        "Wissenswertes",
        "Verbandsmitgliedschaften",
        "Sponsoren und Spenden",
        "Qualitätssiegel",
        "Soziale Medien",
        "Pressemitteilungen",
        "Instagram",
        "TikTok",
    ],
    "en": [
        "Language Selection",
        "Information",
        "Legal Notice",
        "Privacy",
        "Contact",
        "Worth Knowing",
        "Association Memberships",
        "Sponsors and Donations",
        "Seal of Quality",
        "Social Media",
        "Press Releases",
        "Instagram",
        "TikTok",
    ],
    "ja": [
        "言語選択",
        "情報 ",
        "インプリント ",
        "データ保護 ",
        "連絡先 ",
        '知るべきこと "を知る',
        '協会会員 "であること',
        'スポンサーと寄付 "のページです',
        '品質の証 "である',
        'ソーシャルメディア',
        'プレスリリース "をご覧ください',
        "Instagram ",
        "TikTok ",
    ],
    "un": [
        "Nyelvválasztás",
        "Információ",
        "Impresszum",
        "Adatvédelem",
        "Kapcsolat",
        "Érdemes tudni",
        "Egyesületi tagság",
        "Szponzorok és adományok",
        "Minőségi pecsét",
        "Közösségi média",
        "Sajtóközlemények",
        "Instagram",
        "TikTok",
    ],
}