export const dojo = {
    "de": [
        "Unser Dojo",
        "Wir freuen uns darauf, Sie in unserer Karate-Sparte begrüßen zu dürfen. Unsere Sporthalle befindet sich in einer günstigen Lage und ist leicht zu erreichen. Bitte zögern Sie nicht uns zu kontaktieren, falls Sie Hilfe bei der Anfahrt benötigen.",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "en": [
        "Our Dojo",
        "We look forward to welcoming you to our karate division. Our gym is conveniently located and easy to get to. Please do not hesitate to contact us if you need any help with directions.",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "ja": [
        "私たちの道場",
        "空手部へのご参加をお待ちしております。 私たちのスポーツホールは、便利な場所にあり、簡単にアクセスできます。案内が必要な場合は、ご遠慮なくお問い合わせください。",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "un": [
        "A mi Dojo-nk",
        "Szeretettel várjuk Önt karate részlegünkben. Edzőtermünk kényelmes helyen található és könnyen megközelíthető. Kérjük, ne habozzon kapcsolatba lépni velünk, ha segítségre van szüksége az útbaigazítással kapcsolatban.",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
}

export const times = {
    "de": [
        "Unsere Trainingszeiten",
        "Unsere Karate-Sparte bietet regelmäßige Trainingseinheiten an drei Tagen in der Woche an. Dienstags und Donnerstags finden die Trainings von 18:00 Uhr bis 20:30 Uhr statt, während Freitags von 18:00 Uhr bis 20:30 Uhr spezielles Training für Fortgeschrittene  angeboten wird. Für diejenigen, die ihre Fähigkeiten auf die nächste Stufe bringen möchten, bieten wir auch ein Spezialtraining am Samstag von 8:00 Uhr bis 12:00 Uhr an.",
        "Di: 18:00 - 20:30",
        "Do: 18:00 - 20:30",
        "Fr: 18:00 - 20:30",
        "Sa: 08:00 - 12:00",
    ],
    "en": [
        "Our training times",
        "Our karate division offers regular training sessions on three days in the week. On Tuesdays and Thursdays, training sessions are held from 18:00 to 20:30 while on Fridays from 18:00 to 20:30 special training for advanced students  is offered. For those who want to take their skills to the next level, we also offer special training on Saturdays from 8:00 am to 12:00 noon.",
        "Tu: 18:00 - 20:30",
        "Th: 18:00 - 20:30",
        "Fr: 18:00 - 20:30",
        "Sa: 08:00 - 12:00",
    ],
    "ja": [
        "トレーニング時間",
        "空手部では週3日、定期的に練習を行っています。火曜日と木曜日は18時から20時30分まで、金曜日は18時から20時30分まで、上級者向けの特別なトレーニングが行われます。さらにレベルアップしたい方のために、土曜日の8:00～12:00に特別講習も行っています。",
        "火曜日: 18:00 - 20:30",
        "木曜日: 18:00 - 20:30",
        "金曜日: 18:00 - 20:30",
        "土曜日: 08:00 - 12:00",
    ],
    "un": [
        "Edzésidőpontjaink",
        "Karate szakosztályunk a hét három napján rendszeres edzéseket tart. Kedden és csütörtökön 18:00 és 20:30 között tartjuk az edzéseket, míg pénteken 18:00 és 20:30 között speciális edzéseket kínálunk a haladóknak. Azok számára, akik szeretnék tudásukat a következő szintre emelni, szombatonként 8:00 és 12:00 óra között speciális edzéseket is kínálunk.",
        "Kedd: 18:00 - 20:30",
        "Csütörtök: 18:00 - 20:30",
        "Péntek : 18:00 - 20:30",
        "Szombat: 08:00 - 12:00",
    ],
}

export const offers = {
    "de": [
        "Unsere Angebote an euch",
        "Im folgenden sind unsere 5 Mitgliedschaften aufgeführt. Solltest du Interesse haben, dann kannst du gerne ein Probetraining vereinbaren oder eine Kurzzeitmitgliedschaft buchen. Alle weiteren Informationen erhaltest du nach Kontaktaufnahme bei uns",
        "Normale Mitgliedschaft",
        "Mit 65€ jedes Halbe Jahr erhaltest du unsere Normale Mitgliedschaft beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Das Familien Angebot",
        "Unser Familien Angebot zielt auf Sportbegeisterte Familien ab. Nicht nur du, sondern auch dein Kind beziehungsweise deine Partner/-in kann zu einem besseren Angebot mittrainieren. Dies kann als Volljährige Person erworben werden, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert. Ab dem 2. Mitglied, Zahlt der Höchsteingestufte normal.",
        "Speziell für Schüler, Studenten und Azubis",
        "Mit 55€ jedes Halbe Jahr erhalten unsere Schüler, Studenten und Azubis eine günstigere Normale Mitgliedschaft. Dies beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Unser Kinderangebot",
        "Auch unsere Kinder werden im Vergleich zu einer Normalen Mitgliedschaft begünstigt, mit 45€ jedes Halbe Jahr erhalten Sie eine günstigere Normale Mitgliedschaft. Dies beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Kurzzeitmitgliedschaft",
        "Als einer der wenigen Kampfsport Verein / Schulen bietet Kenkyo erstmals Kurzzeitmitgliedschaften an. Für einmalig 30€ kannst du innerhalb 3 Monate so oft Trainieren kommen wie du möchtest. Danach wirst du automatisch gekündigt und kannst keine weitere Kurzzeitmitgliedschaft buchen. Hast du also weiterhin Interesse, stehen die obige Angebote offen.",
        "Monate",
        "Zu den unten genannten Kosten, kommen ebenfalls 20€ Verwaltungsaufwand.",
    ],
    "en": [
        "Our Offers to You",
        " Below are our 5 memberships. If you are interested, you are welcome to arrange a trial training or book a short-term membership. You will receive all further information after contacting us",
        "Normal Membership",
        "With 65€ every half year you get our normal membership which includes the participation in all training sessions which are provided by us. You can buy this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed",
        "The Family Offer",
        "Our family offer is aimed at sports enthusiastic families. Not only you, but also your child or partner can train at a better offer. This can be purchased as an adult person, it can be canceled monthly, otherwise your membership will be automatically renewed. From the 2nd member, pays the Höchsteingestufte normal.",
        "Especially for pupils, students and trainees",
        "With 55€ every half year, our pupils, students and trainees receive a cheaper normal membership. This includes the participation in all training sessions which are provided by us. You can purchase this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed.",
        "Our children's offer",
        "Also our children are favored compared to a normal membership, with 45€ every half year you get a cheaper normal membership. This includes the participation in all training sessions which are provided by us. You can purchase this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed.",
        "Short Term Membership",
        "As one of the few martial arts club / schools Kenkyo offers for the first time short-term memberships. For a one-time fee of 30€ you can come as often as you want to train within 3 months. After that, you will be automatically canceled and can not book another short-term membership. So if you are still interested, the above offers are open.",
        "months",
        "In addition to the costs mentioned below, there is also an administrative cost of 20€.",
    ],
    "ja": [
        "当社からお客様へのご提案",
        '"5つのメンバーシップ "をご紹介します。ご興味のある方は、ぜひ体験トレーニングや短期会員登録のご予約をお願いします。お問い合わせいただいた後、すべての詳細情報をお送りします」。',
        '通常会員 "であること。',
        "「半年ごとに65€で、私たちが提供するすべてのトレーニングセッションへの参加を含む通常の会員権を得ることができます。大人で購入すると、毎月解約でき、そうでない場合は自動更新される」。",
        "ファミリーオファー ",
        'ファミリーオファー "は、スポーツが好きなご家族を対象としています。自分だけでなく、子どもやパートナーも、より良い条件でトレーニングすることができます。これは大人として購入することができ、毎月解約することができ、そうでない場合は会員が自動的に更新されます。2人目以降は、最高額の会員が通常料金を支払う。',
        "特に児童・生徒・研修生向け ",
        "「半期ごとに55ユーロで、生徒、学生、研修生が通常の会員より安く利用できます。これには、当社が提供するすべてのトレーニングへの参加も含まれます。満年齢で購入できる、毎月解約できる、それ以外は自動更新される」。",
        "私たちの子どもたちの提案",
        "「また、子どもたちには、半年ごとに45ユーロを支払うことで、通常の会員より安く利用できる特典もあります。これには、当社が提供するすべてのトレーニングへの参加も含まれます。大人で購入すると、毎月解約でき、それ以外は自動更新されます。",
        '短期会員 "であること。',
        '数少ない武道クラブ／スクール "である建協が、初めて短期会員制を導入。1回30€で、3ヶ月間何度でもトレーニングができます。それ以降は自動的にキャンセルとなり、再度短期会員を予約することはできません。だから、もしあなたがまだ興味を持っているならば、上記のオファーはあなたに開かれたものです」。',
        "月 ",
        "後述の費用に加えて、事務手数料として20ユーロがかかります。"

    ],
    "un": [
        "Ajánlataink Önnek",
        "Az alábbi 5 tagságunk. Ha felkeltettük érdeklődését, szívesen látjuk, ha próbatanfolyamot szervez vagy rövid távú tagságot foglal. Minden további információt a kapcsolatfelvételt követően kap meg",
        "Normál tagság",
        "Félévente 65€-ért megkapod a normál tagságunkat, amely magában foglalja a részvételt az összes általunk biztosított edzésen. Ezt felnőttként is megvásárolhatod, havonta lemondható, egyébként a tagságod automatikusan megújul",
        "A családi ajánlat",
        "Családi ajánlatunk a sportot szerető családoknak szól. Nemcsak Ön, hanem gyermeke vagy partnere is jobb ajánlatot kaphat. Ezt felnőttként lehet megvásárolni, havonta lemondható, ellenkező esetben a tagság automatikusan megújul. A 2. tagtól kezdve a legmagasabb tag a normál díjat fizeti,",
        "Különösen a tanulók, hallgatók és gyakornokok számára",
        "Félévente 55€-val olcsóbb normál tagságot kapnak diákjaink, hallgatóink és gyakornokaink. Ez magában foglalja az általunk biztosított valamennyi képzésen való részvételt. Ezt nagykorú személyként lehet megvásárolni, havonta felmondható, ellenkező esetben a tagság automatikusan megújul",
        "Gyermekeink ajánlata",
        "Gyermekeinknek is különleges ajánlatot kínálunk a normál tagsághoz képest, félévente 45€-val olcsóbban kapnak normál tagságot. Ez magában foglalja az általunk biztosított valamennyi képzésen való részvételt. Ezt felnőttként is megvásárolhatod, havonta lemondható, egyébként a tagságod automatikusan megújul",
        "Rövid távú tagság",
        "A Kenkyo azon kevés harcművészeti klubok/iskolák egyikeként először kínál rövid távú tagságot. Egyszeri 30€-ért 3 hónapon belül annyiszor edzhetsz, ahányszor csak szeretnél. Ezt követően automatikusan törlésre kerül, és nem foglalhat újabb rövid távú tagságot. Tehát ha még mindig érdekel, a fenti ajánlatok nyitva állnak számodra.",
        "hónapok",
        "Az alább említett költségeken kívül 20 euró adminisztrációs költség is felmerül.",
    ],
}
